#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.local/share/fnm:$PATH"
export MANPAGER='nvim +Man!'
export MANWIDTH=999



eval "$(fnm env --shell zsh --use-on-cd)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"


